<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	
	
  <ItemGroup>
	  <PackageReference Include="ClosedXML" Version="0.105.0" />
	  <PackageReference Include="Hangfire" Version="1.8.21" />
	  <PackageReference Include="Hangfire.AspNetCore" Version="1.8.21" />
	  <PackageReference Include="Hangfire.Core" Version="1.8.21" />
	  <PackageReference Include="Hangfire.MemoryStorage" Version="1.8.1.2" />
	  <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="8.0.0" />
	  <PackageReference Include="Quartz" Version="3.15.0" />
	  <PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.0" />
	  <PackageReference Include="Quartz.Serialization.Json" Version="3.15.0" />
	  <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	  <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	  <PackageReference Include="CloudinaryDotNet" Version="1.27.4" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="8.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.10" />
	  <PackageReference Include="StackExchange.Redis" Version="2.8.24" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZLearn.Application\ZLearn.Application.csproj" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="External\Quartz\up_migration.sql" />
		<EmbeddedResource Include="External\Quartz\down_migration.sql" />
	</ItemGroup>

</Project>
