version: "3.8"
services:
  zlearn_web:
    container_name: 'zlearn_web'
    image: hoangcndev/zlearn:zlearn_web-1.0
    ports:
      - "<out-port>:80"
    volumes:
      - /hoangcn/backup:/app/backup
    environment:
      - ADMIN_PASSWORD=
      - ASPNETCORE_ENVIRONMENT=Production
      - CONNECTION_STRING_POSTGRES=
      - JWT_SECRET_KEY=
      - CONNECTION_STRING_REDIS=
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - CLOUDINARY_NAME=
      - CLOUDINARY_API_KEY=
      - CLOUDINARY_API_SECRET=
      - GROQ_API_KEY=
      - CONNECTION_STRING_MONGODB=mongodb://localhost:27017
      - MONGODB_DATABASE_NAME=
    networks:
      - shared-network
    depends_on:
      - pgdb
      - redis