<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Template\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\logo-light-blue.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="6.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZLearn.Application\ZLearn.Application.csproj" />
    <ProjectReference Include="..\ZLearn.Infras\ZLearn.Infras.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="wwwroot\images\banner-light.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
