<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Zlearn.V2.Domain\Zlearn.V2.Domain.csproj" />
    <ProjectReference Include="..\ZLearn.Domain\ZLearn.Domain.csproj" />
    <ProjectReference Include="..\ZLearn.Application\ZLearn.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
